wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    start_time: 1708224942
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      4: 3.7.3
      5: 0.12.15
      8:
      - 8
batch_size:
  desc: null
  value: 512
epochs:
  desc: null
  value: 150
learning_rate:
  desc: null
  value: 0.03
ngpus:
  desc: null
  value: 4
